name: Terraform Deploy (Dev)

on:
  push:
    branches:
      - main
    paths:
      - 'architecture_jun/envs/dev/**'

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: architecture_jun/envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Decrypt terraform.tfvars
        run: |
            gpg --quiet --batch --yes --decrypt \
              --passphrase="${{ secrets.TFVARS_PASSPHRASE }}" \
              --output envs/dev/terraform.tfvars envs/dev/terraform.tfvars.gpg

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_example: ${{ secrets.TF_VAR_EXAMPLE }} # 필요한 환경변수 설정
